# Generated by Django 2.0 on 2018-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashim', '0003_auto_20180102_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bashquote',
            name='comics',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на комикс'),
        ),
    ]
