# Generated by Django 2.0 on 2018-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashim', '0006_auto_20180103_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='bashquote',
            name='comics_img_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
