# Generated by Django 2.0 on 2018-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashim', '0007_bashquote_comics_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bashquote',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рейтинг'),
        ),
    ]
